CREATE TABLE IF NOT EXISTS PARTIDOS (
  Numero INT PRIMARY KEY,
  Nome VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS CARGOS (
  IDCargo INT PRIMARY KEY,
  NomeCargo VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS CANDIDATOS (
  Numero INT PRIMARY KEY,
  Nome VARCHAR(200) NOT NULL,
  IDCargo INT NOT NULL,
  IDPartido INT NOT NULL,
    CONSTRAINT ID_CARGO_CANDIDATOS_CARGOS FOREIGN KEY(IDCargo) REFERENCES CARGOS(IDCargo),
      CONSTRAINT ID_PARTIDO_CANDIDATOS_PARTIDOS FOREIGN KEY(IDPartido) REFERENCES PARTIDOS(Numero)
);

CREATE TABLE IF NOT EXISTS ZONAS_SECOES (
  IDZona INT PRIMARY KEY,
  NumeroSecao INT UNIQUE KEY,
  NumeroZona INT UNIQUE KEY,
  Qtde_eleitores INT NOT NULL
);

CREATE TABLE IF NOT EXISTS VOTACOES (
  IDCandidato INT NOT NULL,
  IDZona INT NOT NULL,
  NumeroSecao INT NOT NULL,
  Quantidade INT NOT NULL,
  CONSTRAINT ID_CANDIDATO_VOTACOES_CANDIDATOS FOREIGN KEY(IDCandidato) REFERENCES CANDIDATOS(Numero),
  CONSTRAINT ID_ZONA_VOTACOES_ZONA FOREIGN KEY(IDZona) REFERENCES ZONAS_SECOES(IDZona),
  CONSTRAINT ID_SECAO_VOTACOES_SECAO FOREIGN KEY(NumeroSecao) REFERENCES ZONAS_SECOES(NumeroSecao)
);
